server:
  port: 10002
spring:
  application:
    name: config-ssm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cartype?characterEncoding=utf-8&serverTimezone=UTC
    password:
    username: root
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml
myname: dongfan-zhangsan666
